### ISSUE TITLE
Self Service FileVault And SecureToken. broken in 10.13.3

### ISSUE THREAD

**Issue by GreentreeIRL** [ToplessBanana/tutorials#1]
Looks like this is broken with 10.13.

**Comment by jkish2** [comment]
Just tested this workflow on a fresh system running macOS 10.13.3 and did not receive any errors. The mobile account that I was logged in with successfully received SecureToken and FileVault was enabled. What's the error that you're seeing on your end?

```
[STEP 1 of 5]

--

Executing Policy Enable FileVault

[STEP 2 of 5]

Running script enable_FileVault.sh...
Script exit code: 0
Script result: Recovery key = 'XXXX-XXXX-XXXX-XXXX-XXXX-XXXX'
Started APFS operation
UpdatePreboot: Commencing operation to update the Preboot Volume for Target Volume disk1s1 Macintosh HD
UpdatePreboot: The Target Volume's OpenDirectory (non-special kind) user count is 2 and the Recovery (any of 3 kinds) user count is 1
UpdatePreboot: No custom Open Directory path given
UpdatePreboot: Using GivenVolumeMountPointOrNilIfNotMounted for the MacOSSearchPath
UpdatePreboot: Using MacOSSearchPath's child dslocal path for the OpenDirectorySearchPath
UpdatePreboot: MacOS Search Path = (nil=NotMounted) = /
UpdatePreboot: Open Directory Database Search Path = (nil=MacOSSearchPathNotMounted) = /var/db/dslocal/nodes/Default
UpdatePreboot: Preserve EncryptedRootPList When No-OD = 0
UpdatePreboot: Successfully opened Open Directory database; setting AuthODNodeOrNil accordingly
UpdatePreboot: Mounting and ensuring as mounted the related Preboot Volume
UpdatePreboot: Preboot Volume = disk1s2 Preboot
UpdatePreboot: Taking mount hold on Preboot Volume
UpdatePreboot: Preboot Volume Target Directory = /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B
UpdatePreboot: Considering APFS Crypto User 68757773-342D-4D4E-BD55-984FBF8DED73
UpdatePreboot: Defaulting and requiring that this be an Open Directory User
UpdatePreboot: Treating this APFS Crypto User to be, and requiring to match, an Open Directory User
UpdatePreboot: Correlated APFS Volume Crypto User with Open Directory User 68757773-342D-4D4E-BD55-984FBF8DED73 aka "ADMINUSER"
UpdatePreboot: Reading JPEG user picture of length 27253 from Open Directory database
UpdatePreboot: All required data for this Open Directory user has been obtained
UpdatePreboot: Parameters for EFILoginUserGraphics count=1 "unlockOptions"="0"
UpdatePreboot: Before render EFILoginUserGraphics user (graphics/audio) resources Name=ADMINUSER PictureSize=(NoneIsOK)=27253 HintOptional=(null)
UpdatePreboot: After render EFILoginUserGraphics Data=(0=Error)=0x7f8ebdd18680=623053
UpdatePreboot: Before rendering EFILoginUserNamesData resources UserArrayCount=2
UpdatePreboot: After rendering EFILoginUserNamesData Data=(NULL=Skip)=0x7f8ebdd17770 DataItemCount=2
UpdatePreboot: Successfully added a macOS OD User to the building dictionary
UpdatePreboot: Successfully processed APFS Volume Crypto User 68757773-342D-4D4E-BD55-984FBF8DED73
UpdatePreboot: Error for this processed user was 0
UpdatePreboot: Considering APFS Crypto User B7CB1FBD-EA79-48B6-88A5-2415C768CD06
UpdatePreboot: Defaulting and requiring that this be an Open Directory User
UpdatePreboot: Treating this APFS Crypto User to be, and requiring to match, an Open Directory User
UpdatePreboot: Correlated APFS Volume Crypto User with Open Directory User B7CB1FBD-EA79-48B6-88A5-2415C768CD06 aka "USERNAME"
UpdatePreboot: All required data for this Open Directory user has been obtained
UpdatePreboot: Parameters for EFILoginUserGraphics count=0 "unlockOptions"="(null)"
UpdatePreboot: Before render EFILoginUserGraphics user (graphics/audio) resources Name=Jayson Kish (DEMO ACCOUNT) PictureSize=(NoneIsOK)=0 HintOptional=(null)
UpdatePreboot: After render EFILoginUserGraphics Data=(0=Error)=0x7f8ebde29f50=270987
UpdatePreboot: Before rendering EFILoginUserNamesData resources UserArrayCount=2
UpdatePreboot: After rendering EFILoginUserNamesData Data=(NULL=Skip)=0x7f8ebde2b740 DataItemCount=2
UpdatePreboot: Successfully added a macOS OD User to the building dictionary
UpdatePreboot: Successfully processed APFS Volume Crypto User B7CB1FBD-EA79-48B6-88A5-2415C768CD06
UpdatePreboot: Error for this processed user was 0
UpdatePreboot: Considering APFS Crypto User EBC6C064-0000-11AA-AA11-00306543ECAC
UpdatePreboot: This is the Personal Recovery Key for this Volume
UpdatePreboot: Treating this APFS Crypto User as a Personal Recovery Key User
UpdatePreboot: Looking for in-target-MacOS Configuration Profiles Personal Recovery Key Escrow PList at /var/db/ConfigurationProfiles/Settings/com.apple.security.FDERecoveryKeyEscrow.EFI.plist
UpdatePreboot: Escrow is available
UpdatePreboot: Did obtain Location/URL = IT Service Desk
UpdatePreboot: Did obtain optional Device/ServiceRecord = "XXXXXXXXXXXX"
UpdatePreboot: Did obtain optional SerialNumber = "XXXXXXXXXXXX"
UpdatePreboot: Parameters for EFILoginUserGraphics = {"Recovery Record Number" = XXXXXXXXXXXX;"Recovery Redirect URL" = "IT Service Desk";"Recovery Serial Number" = XXXXXXXXXXXX;}
UpdatePreboot: Before rendering EFILoginUserGraphics user resources for type = EFI Login Personal Recovery Key User
UpdatePreboot: After rendering EFILoginUserGraphics Data=(0=Error)=0x7f8ebdf1e650=39469
UpdatePreboot: Successfully added a Personal Recovery Key User to the building dictionary
UpdatePreboot: Successfully processed APFS Volume Crypto User EBC6C064-0000-11AA-AA11-00306543ECAC
UpdatePreboot: Error for this processed user was 0
UpdatePreboot: Error among all processed users was 0
UpdatePreboot: At least one RECOVERY-type(s) user was processed successfully, in the presence of at least one successfully-processed OD user, so clearing among-all-users error if any
UpdatePreboot: The Encrypted Root PList File content is ready
UpdatePreboot: Not encrypting the Encrypted Root PList File content
UpdatePreboot: Encrypted Root PList File to be created path will or would be /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EncryptedRoot.plist.wipekey
UpdatePreboot: Proceeding to write Encrypted Root PList, creating a path as neccessary
UpdatePreboot: Successfully wrote Encrypted Root PList File
UpdatePreboot: DiskManagement Info PList File path will be /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/var/db/CryptoUserInfo.plist
UpdatePreboot: Successfully wrote DiskManagement Info PList File
UpdatePreboot: Checking for existence of Static EFI Resources directory /usr/standalone/i386/EfiLoginUI
UpdatePreboot: Before copying contents of directory of Static EFI Resources at /usr/standalone/i386/EfiLoginUI into directory /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/usr/standalone/i386
UpdatePreboot: After copying error=(0=success)=0
UpdatePreboot: Looking for locale list on macOS on Target Volume
UpdatePreboot: Locale list item count is 1
UpdatePreboot: Before rendering EFILoginInterfaceGraphics global localized resources
UpdatePreboot: After rendering EFILoginInterfaceGraphics FileNamesAndData=(0=error)=0x7f8ebdd1b140=11
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/loginui.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/flag_picker.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/preferences.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/battery.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/appleLogo.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/sound.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/unknown_userUI.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/disk_passwordUI.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/guest_userUI.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/Lucida13.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/Lucida13White.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Generating AdminUserList for Recovery purposes
UpdatePreboot: Considering admin user FFFFEEEE-DDDD-CCCC-BBBB-AAAA00000000
UpdatePreboot: Considering admin user 68757773-342D-4D4E-BD55-984FBF8DED73
UpdatePreboot: Error among all processed admin users was 0
UpdatePreboot: Writing Admin User Info File to path /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/var/db/AdminUserRecoveryInfo.plist
UpdatePreboot: Successfully wrote Admin User Info File
UpdatePreboot: Checking for existence of Secure Access Token file /var/db/dslocal/nodes/Default/secureaccesstoken.plist
UpdatePreboot: Before copying Secure Access Token file /var/db/dslocal/nodes/Default/secureaccesstoken.plist into directory /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/var/db
UpdatePreboot: After copying error=(0=success)=0
UpdatePreboot: Releasing mount hold on Preboot Volume
UpdatePreboot: Unmounting Preboot Volume
UpdatePreboot: Did unmount Preboot Volume err=(ignored)=-69888
UpdatePreboot: Doing memory releases
UpdatePreboot: Exiting Update Preboot operation with overall error=(0=success)=0Finished APFS operation

[STEP 3 of 5]

[STEP 4 of 5]

Inventory will be updated when all queued actions in Self Service are complete.

[STEP 5 of 5]
```

**Comment by GreentreeIRL** [comment]
Where does it store the log?

Sorry been working on a number of things to get our deployment correct,

I tested it in 10.13.2 and works fine but when I tested it with 10.13.3 it errors out on multiple machines I’m out of the office now but I can try again tomorrow it is possible another policy is screwing this up on me.

Sent from my iPhone

On 25 Jan 2018, at 17:39, Jayson Kish <notifications@github.com<mailto:notifications@github.com>> wrote:


Just tested this workflow on a fresh system running macOS 10.13.3 and did not receive any errors. The mobile account that I was logged in with successfully received SecureToken and FileVault was enabled. What's the error that you're seeing on your end?

[STEP 1 of 5]

--

Executing Policy Enable FileVault

[STEP 2 of 5]

Running script enable_FileVault.sh...
Script exit code: 0
Script result: Recovery key = 'XXXX-XXXX-XXXX-XXXX-XXXX-XXXX'
Started APFS operation
UpdatePreboot: Commencing operation to update the Preboot Volume for Target Volume disk1s1 Macintosh HD
UpdatePreboot: The Target Volume's OpenDirectory (non-special kind) user count is 2 and the Recovery (any of 3 kinds) user count is 1
UpdatePreboot: No custom Open Directory path given
UpdatePreboot: Using GivenVolumeMountPointOrNilIfNotMounted for the MacOSSearchPath
UpdatePreboot: Using MacOSSearchPath's child dslocal path for the OpenDirectorySearchPath
UpdatePreboot: MacOS Search Path = (nil=NotMounted) = /
UpdatePreboot: Open Directory Database Search Path = (nil=MacOSSearchPathNotMounted) = /var/db/dslocal/nodes/Default
UpdatePreboot: Preserve EncryptedRootPList When No-OD = 0
UpdatePreboot: Successfully opened Open Directory database; setting AuthODNodeOrNil accordingly
UpdatePreboot: Mounting and ensuring as mounted the related Preboot Volume
UpdatePreboot: Preboot Volume = disk1s2 Preboot
UpdatePreboot: Taking mount hold on Preboot Volume
UpdatePreboot: Preboot Volume Target Directory = /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B
UpdatePreboot: Considering APFS Crypto User 68757773-342D-4D4E-BD55-984FBF8DED73
UpdatePreboot: Defaulting and requiring that this be an Open Directory User
UpdatePreboot: Treating this APFS Crypto User to be, and requiring to match, an Open Directory User
UpdatePreboot: Correlated APFS Volume Crypto User with Open Directory User 68757773-342D-4D4E-BD55-984FBF8DED73 aka "ADMINUSER"
UpdatePreboot: Reading JPEG user picture of length 27253 from Open Directory database
UpdatePreboot: All required data for this Open Directory user has been obtained
UpdatePreboot: Parameters for EFILoginUserGraphics count=1 "unlockOptions"="0"
UpdatePreboot: Before render EFILoginUserGraphics user (graphics/audio) resources Name=ADMINUSER PictureSize=(NoneIsOK)=27253 HintOptional=(null)
UpdatePreboot: After render EFILoginUserGraphics Data=(0=Error)=0x7f8ebdd18680=623053
UpdatePreboot: Before rendering EFILoginUserNamesData resources UserArrayCount=2
UpdatePreboot: After rendering EFILoginUserNamesData Data=(NULL=Skip)=0x7f8ebdd17770 DataItemCount=2
UpdatePreboot: Successfully added a macOS OD User to the building dictionary
UpdatePreboot: Successfully processed APFS Volume Crypto User 68757773-342D-4D4E-BD55-984FBF8DED73
UpdatePreboot: Error for this processed user was 0
UpdatePreboot: Considering APFS Crypto User B7CB1FBD-EA79-48B6-88A5-2415C768CD06
UpdatePreboot: Defaulting and requiring that this be an Open Directory User
UpdatePreboot: Treating this APFS Crypto User to be, and requiring to match, an Open Directory User
UpdatePreboot: Correlated APFS Volume Crypto User with Open Directory User B7CB1FBD-EA79-48B6-88A5-2415C768CD06 aka "USERNAME"
UpdatePreboot: All required data for this Open Directory user has been obtained
UpdatePreboot: Parameters for EFILoginUserGraphics count=0 "unlockOptions"="(null)"
UpdatePreboot: Before render EFILoginUserGraphics user (graphics/audio) resources Name=Jayson Kish (DEMO ACCOUNT) PictureSize=(NoneIsOK)=0 HintOptional=(null)
UpdatePreboot: After render EFILoginUserGraphics Data=(0=Error)=0x7f8ebde29f50=270987
UpdatePreboot: Before rendering EFILoginUserNamesData resources UserArrayCount=2
UpdatePreboot: After rendering EFILoginUserNamesData Data=(NULL=Skip)=0x7f8ebde2b740 DataItemCount=2
UpdatePreboot: Successfully added a macOS OD User to the building dictionary
UpdatePreboot: Successfully processed APFS Volume Crypto User B7CB1FBD-EA79-48B6-88A5-2415C768CD06
UpdatePreboot: Error for this processed user was 0
UpdatePreboot: Considering APFS Crypto User EBC6C064-0000-11AA-AA11-00306543ECAC
UpdatePreboot: This is the Personal Recovery Key for this Volume
UpdatePreboot: Treating this APFS Crypto User as a Personal Recovery Key User
UpdatePreboot: Looking for in-target-MacOS Configuration Profiles Personal Recovery Key Escrow PList at /var/db/ConfigurationProfiles/Settings/com.apple.security.FDERecoveryKeyEscrow.EFI.plist
UpdatePreboot: Escrow is available
UpdatePreboot: Did obtain Location/URL = IT Service Desk
UpdatePreboot: Did obtain optional Device/ServiceRecord = "XXXXXXXXXXXX"
UpdatePreboot: Did obtain optional SerialNumber = "XXXXXXXXXXXX"
UpdatePreboot: Parameters for EFILoginUserGraphics = {"Recovery Record Number" = XXXXXXXXXXXX;"Recovery Redirect URL" = "IT Service Desk";"Recovery Serial Number" = XXXXXXXXXXXX;}
UpdatePreboot: Before rendering EFILoginUserGraphics user resources for type = EFI Login Personal Recovery Key User
UpdatePreboot: After rendering EFILoginUserGraphics Data=(0=Error)=0x7f8ebdf1e650=39469
UpdatePreboot: Successfully added a Personal Recovery Key User to the building dictionary
UpdatePreboot: Successfully processed APFS Volume Crypto User EBC6C064-0000-11AA-AA11-00306543ECAC
UpdatePreboot: Error for this processed user was 0
UpdatePreboot: Error among all processed users was 0
UpdatePreboot: At least one RECOVERY-type(s) user was processed successfully, in the presence of at least one successfully-processed OD user, so clearing among-all-users error if any
UpdatePreboot: The Encrypted Root PList File content is ready
UpdatePreboot: Not encrypting the Encrypted Root PList File content
UpdatePreboot: Encrypted Root PList File to be created path will or would be /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EncryptedRoot.plist.wipekey
UpdatePreboot: Proceeding to write Encrypted Root PList, creating a path as neccessary
UpdatePreboot: Successfully wrote Encrypted Root PList File
UpdatePreboot: DiskManagement Info PList File path will be /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/var/db/CryptoUserInfo.plist
UpdatePreboot: Successfully wrote DiskManagement Info PList File
UpdatePreboot: Checking for existence of Static EFI Resources directory /usr/standalone/i386/EfiLoginUI
UpdatePreboot: Before copying contents of directory of Static EFI Resources at /usr/standalone/i386/EfiLoginUI into directory /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/usr/standalone/i386
UpdatePreboot: After copying error=(0=success)=0
UpdatePreboot: Looking for locale list on macOS on Target Volume
UpdatePreboot: Locale list item count is 1
UpdatePreboot: Before rendering EFILoginInterfaceGraphics global localized resources
UpdatePreboot: After rendering EFILoginInterfaceGraphics FileNamesAndData=(0=error)=0x7f8ebdd1b140=11
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/loginui.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/flag_picker.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/preferences.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/battery.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/appleLogo.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/sound.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/unknown_userUI.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/disk_passwordUI.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/guest_userUI.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/Lucida13.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Writing localized EFI graphics resource file /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/System/Library/Caches/com.apple.corestorage/EFILoginLocalizations/Lucida13White.efires
UpdatePreboot: Successfully wrote EFI resource file
UpdatePreboot: Generating AdminUserList for Recovery purposes
UpdatePreboot: Considering admin user FFFFEEEE-DDDD-CCCC-BBBB-AAAA00000000
UpdatePreboot: Considering admin user 68757773-342D-4D4E-BD55-984FBF8DED73
UpdatePreboot: Error among all processed admin users was 0
UpdatePreboot: Writing Admin User Info File to path /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/var/db/AdminUserRecoveryInfo.plist
UpdatePreboot: Successfully wrote Admin User Info File
UpdatePreboot: Checking for existence of Secure Access Token file /var/db/dslocal/nodes/Default/secureaccesstoken.plist
UpdatePreboot: Before copying Secure Access Token file /var/db/dslocal/nodes/Default/secureaccesstoken.plist into directory /Volumes/Preboot/3F969E77-9184-4765-8FFC-EABDD745090B/var/db
UpdatePreboot: After copying error=(0=success)=0
UpdatePreboot: Releasing mount hold on Preboot Volume
UpdatePreboot: Unmounting Preboot Volume
UpdatePreboot: Did unmount Preboot Volume err=(ignored)=-69888
UpdatePreboot: Doing memory releases
UpdatePreboot: Exiting Update Preboot operation with overall error=(0=success)=0Finished APFS operation

[STEP 3 of 5]

[STEP 4 of 5]

Inventory will be updated when all queued actions in Self Service are complete.

[STEP 5 of 5]

**Comment by jkish2** [comment]
You can find the log by clicking on "Details" next to the Policy name in the Policy History of the affected computer's inventory record.

**Comment by GreentreeIRL** [comment]
I cleared them out of my jamf instance but will be able to check again in 3/4 hours,

Thanks for getting back to me

Sent from my iPhone

On 25 Jan 2018, at 18:18, Jayson Kish <notifications@github.com<mailto:notifications@github.com>> wrote:


You can find the log by clicking on "Details" next to the Policy name in the Policy History of the affected computer's inventory record.
