### ISSUE TITLE
Never leaves black upgrade screen

### ISSUE THREAD

**Issue by tekie39** [ToplessBanana/tutorials#3]
Seeing a few of the Mac just sit on the Black upgrading screen and they never come out of it. 

Restarting puts them right back into the screen. Thoughts?

**Comment by jkish2** [comment]
Sorry for the delayed response. Which version of macOS were you upgrading, and what version were you upgrading to?

**Comment by tekie39** [comment]
Figured it out, was actually JAMF not updating inventory and thinking it wasn’t upgrade so it was just trying to run the script in a loop. Booting to Safe mode then forcing the inventory update resolved the problem.
Cheers,

Tyrell Goodpaster
IT Administrator
True Fit Corporation
(339)-216-0640

**Comment by jkish2** [comment]
Glad to see you got it resolved. Thanks for the follow up!
